name = "agentic-search"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat_v2", "no_handle_cross_request_promise_resolution"]
main = "@tanstack/react-start/server-entry"

[observability]
enabled = true

[vars]
VITE_CONVEX_URL = "https://astute-quail-141.convex.cloud"
VITE_SITE_URL = "https://astute-quail-141.convex.site"
VITE_DISABLE_AUTH = "true"
