/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestKeyRouteImport } from './routes/api/test-key'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiCsrfTokenRouteImport } from './routes/api/csrf-token'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiSearchStreamRouteImport } from './routes/api/search/stream'
import { Route as ApiSearchProgressRouteImport } from './routes/api/search/progress'
import { Route as ApiSearchControlRouteImport } from './routes/api/search/control'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestKeyRoute = ApiTestKeyRouteImport.update({
  id: '/api/test-key',
  path: '/api/test-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCsrfTokenRoute = ApiCsrfTokenRouteImport.update({
  id: '/api/csrf-token',
  path: '/api/csrf-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchStreamRoute = ApiSearchStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiSearchRoute,
} as any)
const ApiSearchProgressRoute = ApiSearchProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ApiSearchRoute,
} as any)
const ApiSearchControlRoute = ApiSearchControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => ApiSearchRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/csrf-token': typeof ApiCsrfTokenRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/api/test-key': typeof ApiTestKeyRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/search/control': typeof ApiSearchControlRoute
  '/api/search/progress': typeof ApiSearchProgressRoute
  '/api/search/stream': typeof ApiSearchStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/csrf-token': typeof ApiCsrfTokenRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/api/test-key': typeof ApiTestKeyRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/search/control': typeof ApiSearchControlRoute
  '/api/search/progress': typeof ApiSearchProgressRoute
  '/api/search/stream': typeof ApiSearchStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/export': typeof ExportRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/csrf-token': typeof ApiCsrfTokenRoute
  '/api/search': typeof ApiSearchRouteWithChildren
  '/api/test-key': typeof ApiTestKeyRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/search/control': typeof ApiSearchControlRoute
  '/api/search/progress': typeof ApiSearchProgressRoute
  '/api/search/stream': typeof ApiSearchStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparison'
    | '/export'
    | '/history'
    | '/mcp'
    | '/search'
    | '/settings'
    | '/api/$'
    | '/api/chat'
    | '/api/csrf-token'
    | '/api/search'
    | '/api/test-key'
    | '/api/rpc/$'
    | '/api/search/control'
    | '/api/search/progress'
    | '/api/search/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparison'
    | '/export'
    | '/history'
    | '/mcp'
    | '/search'
    | '/settings'
    | '/api/$'
    | '/api/chat'
    | '/api/csrf-token'
    | '/api/search'
    | '/api/test-key'
    | '/api/rpc/$'
    | '/api/search/control'
    | '/api/search/progress'
    | '/api/search/stream'
  id:
    | '__root__'
    | '/'
    | '/comparison'
    | '/export'
    | '/history'
    | '/mcp'
    | '/search'
    | '/settings'
    | '/api/$'
    | '/api/chat'
    | '/api/csrf-token'
    | '/api/search'
    | '/api/test-key'
    | '/api/rpc/$'
    | '/api/search/control'
    | '/api/search/progress'
    | '/api/search/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparisonRoute: typeof ComparisonRoute
  ExportRoute: typeof ExportRoute
  HistoryRoute: typeof HistoryRoute
  McpRoute: typeof McpRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCsrfTokenRoute: typeof ApiCsrfTokenRoute
  ApiSearchRoute: typeof ApiSearchRouteWithChildren
  ApiTestKeyRoute: typeof ApiTestKeyRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-key': {
      id: '/api/test-key'
      path: '/api/test-key'
      fullPath: '/api/test-key'
      preLoaderRoute: typeof ApiTestKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csrf-token': {
      id: '/api/csrf-token'
      path: '/api/csrf-token'
      fullPath: '/api/csrf-token'
      preLoaderRoute: typeof ApiCsrfTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/stream': {
      id: '/api/search/stream'
      path: '/stream'
      fullPath: '/api/search/stream'
      preLoaderRoute: typeof ApiSearchStreamRouteImport
      parentRoute: typeof ApiSearchRoute
    }
    '/api/search/progress': {
      id: '/api/search/progress'
      path: '/progress'
      fullPath: '/api/search/progress'
      preLoaderRoute: typeof ApiSearchProgressRouteImport
      parentRoute: typeof ApiSearchRoute
    }
    '/api/search/control': {
      id: '/api/search/control'
      path: '/control'
      fullPath: '/api/search/control'
      preLoaderRoute: typeof ApiSearchControlRouteImport
      parentRoute: typeof ApiSearchRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiSearchRouteChildren {
  ApiSearchControlRoute: typeof ApiSearchControlRoute
  ApiSearchProgressRoute: typeof ApiSearchProgressRoute
  ApiSearchStreamRoute: typeof ApiSearchStreamRoute
}

const ApiSearchRouteChildren: ApiSearchRouteChildren = {
  ApiSearchControlRoute: ApiSearchControlRoute,
  ApiSearchProgressRoute: ApiSearchProgressRoute,
  ApiSearchStreamRoute: ApiSearchStreamRoute,
}

const ApiSearchRouteWithChildren = ApiSearchRoute._addFileChildren(
  ApiSearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparisonRoute: ComparisonRoute,
  ExportRoute: ExportRoute,
  HistoryRoute: HistoryRoute,
  McpRoute: McpRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCsrfTokenRoute: ApiCsrfTokenRoute,
  ApiSearchRoute: ApiSearchRouteWithChildren,
  ApiTestKeyRoute: ApiTestKeyRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
